In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("1970-2021_DISASTERS.xlsx - emdat data.csv"
,keep_default_na=False,na_values=[''],na_filter=True

)

In [ ]:
len(df)

14644

**שאלת המחקר : מהם הגורמים המשפיעים על חומרת אסונות טבע בעולם, כפי שהיא באה לידי ביטוי בהיקף הנזק האנושי והכלכלי? **

#1. הכרת הדאטה

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14644 entries, 0 to 14643
Data columns (total 47 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Dis No                           14644 non-null  object
 1   Year                             14644 non-null  int64
 2   Seq                              14644 non-null  int64
 3   Glide                            1581 non-null   object
 4   Disaster Group                   14644 non-null  object
 5   Disaster Subgroup                14644 non-null  object
 6   Disaster Type                    14644 non-null  object
 7   Disaster Subtype                 11897 non-null  object
 8   Disaster Subsubtype              1044 non-null   object
 9   Event Name                       3645 non-null   object
 10  Country                          14644 non-null  object
 11  ISO                              14644 non-null  object
 12  Region                           14644 non-null  object
 13  Continent                        14644 non-null  object
 14  Location                         13298 non-null  object
 15  Origin                           3780 non-null   object
 16  Associated Dis                   3232 non-null   object
 17  Associated Dis2                  698 non-null    object
 18  OFDA Response                    1450 non-null   object
 19  Appeal                           2440 non-null   object
 20  Declaration                      3127 non-null   object
 21  Aid Contribution                 677 non-null    float64
 22  Dis Mag Value                    4569 non-null   float64
 23  Dis Mag Scale                    13571 non-null  object
 24  Latitude                         2331 non-null   object
 25  Longitude                        2335 non-null   object
 26  Local Time                       765 non-null    object
 27  River Basin                      1285 non-null   object
 28  Start Year                       14644 non-null  int64
 29  Start Month                      14376 non-null  float64
 30  Start Day                        11577 non-null  float64
 31  End Year                         14644 non-null  int64
 32  End Month                        14095 non-null  float64
 33  End Day                          11650 non-null  float64
 34  Total Deaths                     10199 non-null  float64
 35  No Injured                       3651 non-null   float64
 36  No Affected                      8846 non-null   float64
 37  No Homeless                      2249 non-null   float64
 38  Total Affected                   11041 non-null  float64
 39  Reconstruction Costs ('000 US$)  31 non-null     float64
 40  Insured Damages ('000 US$)       1094 non-null   float64
 41  Total Damages ('000 US$)         4863 non-null   float64
 42  CPI                              14329 non-null  float64
 43  Adm Level                        7855 non-null   object
 44  Admin1 Code                      4581 non-null   object
 45  Admin2 Code                      3965 non-null   object
 46  Geo Locations                    7855 non-null   object
dtypes: float64(15), int64(4), object(28)
memory usage: 5.3+ MB

| עמודה    | הסבר                           |
| -------- | ------------------------------ |
| `Dis No` | מזהה ייחודי של האסון           |
| `Year`   | השנה שבה התרחש האסון           |
| `Seq`    | מספר סידורי פנימי של האירוע    |
| `Glide`  | קוד בינלאומי למעקב אחרי אסונות |

| עמודה                 | הסבר                                               |
| --------------------- | -------------------------------------------------- |
| `Disaster Group`      | קבוצה כללית של האסון (למשל Natural)                |
| `Disaster Subgroup`   | תת קבוצה של האסון (Hydrological / Geological וכו') |
| `Disaster Type`       | סוג האסון המרכזי (Flood, Earthquake וכו')          |
| `Disaster Subtype`    | תת סוג מפורט יותר                                  |
| `Disaster Subsubtype` | תיאור עוד יותר ספציפי של האסון                     |



| עמודה             | הסבר                    |
| ----------------- | ----------------------- |
| `Event Name`      | שם האסון אם קיים        |
| `Origin`          | מקור האסון / כיצד התחיל |
| `Associated Dis`  | אסון נלווה              |
| `Associated Dis2` | אסון נלווה נוסף         |


| עמודה           | הסבר                      |
| --------------- | ------------------------- |
| `Country`       | המדינה שבה התרחש האסון    |
| `ISO`           | קוד ISO של המדינה         |
| `Region`        | אזור גיאוגרפי             |
| `Continent`     | יבשת                      |
| `Location`      | מיקום ספציפי              |
| `Latitude`      | קו רוחב                   |
| `Longitude`     | קו אורך                   |
| `River Basin`   | אגן נהר (בעיקר לשיטפונות) |
| `Geo Locations` | מידע גיאוגרפי נוסף        |


| עמודה           | הסבר            |
| --------------- | --------------- |
| `Dis Mag Value` | ערך עוצמת האסון |
| `Dis Mag Scale` | סולם המדידה     |


| עמודה         | הסבר                 |
| ------------- | -------------------- |
| `Start Year`  | שנת התחלת האסון      |
| `Start Month` | חודש התחלת האסון     |
| `Start Day`   | יום התחלת האסון      |
| `End Year`    | שנת סיום האסון       |
| `End Month`   | חודש סיום האסון      |
| `End Day`     | יום סיום האסון       |
| `Local Time`  | שעה מקומית של האירוע |



| עמודה            | הסבר                        |
| ---------------- | --------------------------- |
| `Total Deaths`   | מספר הרוגים                 |
| `No Injured`     | מספר פצועים                 |
| `No Affected`    | מספר אנשים שהושפעו מהאסון   |
| `No Homeless`    | מספר חסרי הבית              |
| `Total Affected` | סך כלל האנשים שנפגעו/הושפעו |


| עמודה                             | הסבר                        |
| --------------------------------- | --------------------------- |
| `Total Damages ('000 US$)`        | סך הנזק הכלכלי באלפי דולרים |
| `Insured Damages ('000 US$)`      | נזק מבוטח                   |
| `Reconstruction Costs ('000 US$)` | עלויות שיקום                |
| `CPI`                             | מדד מחירים לצרכן            |



OFDA = Office of U.S. Foreign Disaster Assistance
כלומר:
יחידה אמריקאית לסיוע באסונות טבע בעולם.

Appeal = בקשת סיוע בינלאומית
Declaration = הכרזה רשמית על מצב חירום / אסון
Aid Contribution = סכום הסיוע שניתן

In [ ]:
int(df['Total Deaths'].sum())

3690132

In [ ]:
int(df['Total Affected'].sum())

8034968791

In [ ]:
df["Total Damages ('000 US$)"].sum() / 1_000_000

np.float64(3767.301172)

In [ ]:
df.head(6)

,Dis No,Year,Seq,Glide,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,Disaster Subsubtype,Event Name,...,No Homeless,Total Affected,Reconstruction Costs ('000 US$),Insured Damages ('000 US$),Total Damages ('000 US$),CPI,Adm Level,Admin1 Code,Admin2 Code,Geo Locations
0,1970-0013-ARG,1970,13,NaN,Natural,Hydrological,Flood,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,25000.0,15.001282,NaN,NaN,NaN,NaN
1,1970-0109-AUS,1970,109,NaN,Natural,Meteorological,Storm,Tropical cyclone,NaN,Ada,...,NaN,NaN,NaN,NaN,72475.0,15.001282,NaN,NaN,NaN,NaN
2,1970-0044-BEN,1970,44,NaN,Natural,Hydrological,Flood,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,200.0,15.001282,NaN,NaN,NaN,NaN
3,1970-0063-BGD,1970,63,NaN,Natural,Meteorological,Storm,Tropical cyclone,NaN,NaN,...,NaN,3648000.0,NaN,NaN,86400.0,15.001282,NaN,NaN,NaN,NaN
4,1970-0026-BGD,1970,26,NaN,Natural,Meteorological,Storm,NaN,NaN,NaN,...,NaN,110.0,NaN,NaN,NaN,15.001282,NaN,NaN,NaN,NaN
5,1970-0035-BGD,1970,35,NaN,Natural,Hydrological,Flood,NaN,NaN,NaN,...,NaN,10000000.0,NaN,NaN,25000.0,15.001282,NaN,NaN,NaN,NaN

## 1.1 הכרת הערכים החסרים בדאטה

In [ ]:
df.isnull().sum()

Dis No                          0
Year                            0
Seq                             0
Disaster Group                  0
Disaster Subgroup               0
Disaster Type                   0
Disaster Subtype             2030
Disaster Subsubtype         10416
Country                         0
ISO                             0
Region                          0
Continent                       0
Origin                       7706
Associated Dis               8356
Associated Dis2             10462
OFDA Response                9675
Appeal                       9068
Declaration                  8514
Dis Mag Value                7158
Dis Mag Scale                 644
River Basin                  9843
Start Year                      0
Start Month                   159
Start Day                    2021
End Year                        0
End Month                     351
End Day                      1932
Total Deaths                 3099
No Injured                   7390
No Affected                  2195
No Homeless                  8792
Total Affected                  0
Total Damages ('000 US$)     7236
CPI                             0
Adm Level                    4796
Admin1 Code                  7596
Admin2 Code                  7645
Geo Locations                4796
Disaster Duration (Days)     2108
Adjusted Total Damage        7236
Country Code                 2105
GDP                          2188
dtype: int64

In [ ]:
missing_percent = df.isnull().mean()*100
missing_percent.sort_values(ascending=False)

Reconstruction Costs ('000 US$)    99.788309
Aid Contribution                   95.376946
Associated Dis2                    95.233543
Local Time                         94.776017
Disaster Subsubtype                92.870800
Insured Damages ('000 US$)         92.529364
River Basin                        91.225075
OFDA Response                      90.098334
Glide                              89.203769
No Homeless                        84.642174
Latitude                           84.082218
Longitude                          84.054903
Appeal                             83.337886
Declaration                        78.646545
Associated Dis                     77.929527
Event Name                         75.109260
No Injured                         75.068287
Origin                             74.187380
Admin2 Code                        72.924064
Dis Mag Value                      68.799508
Admin1 Code                        68.717564
Total Damages ('000 US$)           66.791860
Adm Level                          46.360284
Geo Locations                      46.360284
No Affected                        39.593007
Total Affected                     24.603933
Start Day                          20.943731
End Day                            20.445234
Disaster Subtype                   18.758536
Location                            9.191478
Dis Mag Scale                       7.327233
End Month                           3.748976
CPI                                 2.151052
Start Month                         1.830101
Region                              0.000000
Continent                           0.000000
Disaster Group                      0.000000
Disaster Subgroup                   0.000000
Disaster Type                       0.000000
Dis No                              0.000000
Year                                0.000000
ISO                                 0.000000
Country                             0.000000
Seq                                 0.000000
Start Year                          0.000000
End Year                            0.000000
Total Deaths                        0.000000
dtype: float64

# 2. ניקוי דאטה

glide - למחוק
event name -למחוק
location - להוריד כי מדובר כאן במחוז
Aid Contribution - להוריד אין ערכים
Latitude
Longitude
Local Time
Reconstruction Costs ('000 US$)
Insured Damages ('000 US$)

OFDA
Appeal
Declaration
**השאלה אם להשאיר אותם והאם זה משפיע על הערך הנזק הכלכלי ר**

In [ ]:
##מחיקת עמודות שלא רלוונטים
drop_cols = [
    'Glide',
    'Event Name',
    'Location',
    'Aid Contribution'
    'Local Time',
    "Reconstruction Costs ('000 US$)",
    "Insured Damages ('000 US$)"
]

df.drop(columns=drop_cols, inplace=True, errors='ignore')

In [ ]:
## בדיקת כפילויות בדאטה
# בדיקת כפילויות מלאות בכל הדאטה

duplicates_count = df.duplicated().sum()

print(f'Total Duplicate Rows: {duplicates_count}')

Total Duplicate Rows: 0

## 2.1 פונקצייה המחשבת את ההפרש של כל אסון בימים

River Basin - להשאיר רלוונטי להצפות
להוסיף  פונקצייה של זמן בעמודת חישוב שתחשב את ההפרש בין התאריכים שקרו ההצפות כדי לדעת את ממשך הזמן

In [ ]:
## הוספת פונקצייה שתחשב את ההפרש שקרו ההצפות כדי לדעת את משך הימים של כל הצפה
import pandas as pd
import numpy as np

# פונקציה לחישוב משך האסון בימים
def calculate_disaster_duration(row):

    try:
        # אם חסר אחד מהערכים → מחזיר NaN
        required_cols = [
            'Start Year',
            'Start Month',
            'Start Day',
            'End Year',
            'End Month',
            'End Day'
        ]

        if row[required_cols].isnull().any():
            return np.nan

        # יצירת תאריך התחלה
        start_date = pd.Timestamp(
            year=int(row['Start Year']),
            month=int(row['Start Month']),
            day=int(row['Start Day'])
        )

        # יצירת תאריך סיום
        end_date = pd.Timestamp(
            year=int(row['End Year']),
            month=int(row['End Month']),
            day=int(row['End Day'])
        )

        # חישוב הפרש ימים
        return (end_date - start_date).days

    except:
        return np.nan


# יצירת עמודה חדשה
df['Disaster Duration (Days)'] = df.apply(
    calculate_disaster_duration,
    axis=1
)

In [ ]:
# כמות ערכים ייחודיים בכל עמודה

unique_values = pd.DataFrame({
    'Column': df.columns,
    'Unique Values Count': [df[col].nunique() for col in df.columns]
})

# מיון מהגבוה לנמוך
unique_values = unique_values.sort_values(
    by='Unique Values Count',
    ascending=False
)

# הצגה
unique_values

                      Column  Unique Values Count
0                     Dis No                14644
37             Geo Locations                 6354
31            Total Affected                 4901
29               No Affected                 3492
36               Admin2 Code                 3445
35               Admin1 Code                 3434
18             Dis Mag Value                 1860
32  Total Damages ('000 US$)                 1519
2                        Seq                 1265
20               River Basin                 1213
30               No Homeless                  840
28                No Injured                  713
27              Total Deaths                  710
12                    Origin                  660
9                        ISO                  228
8                    Country                  228
38  Disaster Duration (Days)                  225
24                  End Year                   52
21                Start Year                   52
1                       Year                   52
33                       CPI                   51
23                 Start Day                   31
26                   End Day                   31
13            Associated Dis                   30
14           Associated Dis2                   29
6           Disaster Subtype                   27
10                    Region                   23
5              Disaster Type                   14
22               Start Month                   12
25                 End Month                   12
7        Disaster Subsubtype                   12
4          Disaster Subgroup                    6
11                 Continent                    5
19             Dis Mag Scale                    5
34                 Adm Level                    3
17               Declaration                    2
16                    Appeal                    2
3             Disaster Group                    1
15             OFDA Response                    1

In [ ]:
# הצגת דוגמאות של שיטפונות עם משך  זמן האסון

flood_examples[
    flood_examples['Disaster Duration (Days)'] > 0
].sort_values(
    by='Disaster Duration (Days)',
    ascending=False
).head(10)

NameError: name 'flood_examples' is not defined

In [ ]:
df.groupby('Disaster Type')['Disaster Duration (Days)'] \
  .mean() \
  .sort_values(ascending=False)

Disaster Type
Drought                  177.750000
Epidemic                  73.379573
Extreme temperature       12.261905
Wildfire                  11.013514
Flood                      8.977375
Volcanic activity          6.280612
Storm                      1.799086
Landslide                  1.247678
Mass movement (dry)        1.000000
Glacial lake outburst      0.500000
Earthquake                 0.029903
Animal accident            0.000000
Insect infestation         0.000000
Impact                     0.000000
Name: Disaster Duration (Days), dtype: float64

## 2.2 מחיקת הרשומות שבהן כל הרשומות הן נאן

In [ ]:
# מחיקת רשומות שבהן אין מידע על הנזק הכלכלי

df = df.dropna(
    subset=[
        'No Affected',
        'Total Affected',

    ],
    how='all'
)

In [ ]:
# בדיקת כמות רשומות לפני המחיקה
rows_before = len(df)

# מחיקת רשומות שאין בהן כלל מידע כלכלי
df = df.dropna(
    subset=[
        "Total Damages ('000 US$)",
        "CPI",
        "GDP",
        "Adjusted Total Damage"
    ],
    how='all'
)

# כמות רשומות אחרי המחיקה
rows_after = len(df)

# כמה רשומות נמחקו
print("Rows before:", rows_before)
print("Rows after:", rows_after)
print("Deleted rows:", rows_before - rows_after)

Rows before: 11041
Rows after: 11041
Deleted rows: 0

## 2.3 בדיקת ערכים קיצוניים ולשנות בהתאם
ערכים קיצוניים לבדוק מהם הערכים ולשנות לחסר

In [ ]:
df.loc[df['Dis Mag Value'] == 59, 'Dis Mag Value'] = np.nan

In [ ]:
df[df['Dis Mag Value'] == 59]

Empty DataFrame
Columns: [Dis No, Year, Seq, Disaster Group, Disaster Subgroup, Disaster Type, Disaster Subtype, Disaster Subsubtype, Country, ISO, Region, Continent, Origin, Associated Dis, Associated Dis2, OFDA Response, Appeal, Declaration, Dis Mag Value, Dis Mag Scale, River Basin, Start Year, Start Month, Start Day, End Year, End Month, End Day, Total Deaths, No Injured, No Affected, No Homeless, Total Affected, Total Damages ('000 US$), CPI, Adm Level, Admin1 Code, Admin2 Code, Geo Locations, Disaster Duration (Days)]
Index: []

[0 rows x 39 columns]

## 2.4 הגדרת CPI בשנת 2021

In [ ]:
df['CPI'] = df['CPI'].fillna(method='ffill')

/tmp/ipykernel_4228/548707370.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['CPI'] = df['CPI'].fillna(method='ffill')

In [ ]:
df['CPI'].isna().sum()

np.int64(0)

In [ ]:
df[df['Year'].isin([2020, 2021])][
    ['Year', 'CPI']
].tail(20)

       Year    CPI
14624  2021  100.0
14625  2021  100.0
14626  2021  100.0
14627  2021  100.0
14628  2021  100.0
14629  2021  100.0
14630  2021  100.0
14631  2021  100.0
14632  2021  100.0
14633  2021  100.0
14634  2021  100.0
14635  2021  100.0
14636  2021  100.0
14637  2021  100.0
14638  2021  100.0
14639  2021  100.0
14640  2021  100.0
14641  2021  100.0
14642  2021  100.0
14643  2021  100.0

In [ ]:
# הצגת ערכי CPI של כל השנים

cpi_by_year = df.groupby('Year')['CPI'].mean()

print(cpi_by_year)

Year
1970     15.001282
1971     15.645257
1972     16.157212
1973     17.155360
1974     19.051854
1975     20.793799
1976     21.988357
1977     23.417971
1978     25.204991
1979     28.041681
1980     31.841107
1981     35.131792
1982     37.285870
1983     38.483651
1984     40.138660
1985     41.561827
1986     42.350699
1987     43.902662
1988     45.692897
1989     47.898497
1990     50.484032
1991     52.622020
1992     54.215845
1993     55.816107
1994     57.271483
1995     58.878183
1996     60.604028
1997     62.020757
1998     62.983501
1999     64.361593
2000     66.534994
2001     68.415379
2002     69.500473
2003     71.078198
2004     72.981129
2005     75.457200
2006     77.891400
2007     80.113393
2008     83.189023
2009     82.893250
2010     84.252733
2011     86.912465
2012     88.710969
2013     90.010440
2014     91.470614
2015     91.579117
2016     92.734479
2017     94.709841
2018     97.023129
2019     98.781448
2020    100.000000
2021    100.000000
Name: CPI, dtype: float64

## 2.5 יצירת מדד כלכלי מותאם אינלפציה Adjusted Total Damage

In [ ]:
# יצירת עמודת נזק כלכלי מותאם אינפלציה

df['Adjusted Total Damage'] = (
    df["Total Damages ('000 US$)"] / df['CPI']
) * 100

# עיגול ל-2 ספרות אחרי הנקודה
df['Adjusted Total Damage'] = df['Adjusted Total Damage'].round(2)

In [ ]:
df[[
    "Total Damages ('000 US$)",
    'CPI',
    'Adjusted Total Damage'
]].head()

   Total Damages ('000 US$)        CPI  Adjusted Total Damage
0                   25000.0  15.001282              166652.42
1                   72475.0  15.001282              483125.37
2                     200.0  15.001282                1333.22
3                   86400.0  15.001282              575950.77
4                       NaN  15.001282                    NaN

2.6 הוספת מדד תמ"ג לנפש מכל מדינה ממקור קבוצת הבנק העולמית
קישור: https://data.worldbank.org/indicator/NY.GDP.MKTP.CD

In [ ]:
df['Country'] = df['Country'].replace({
    'United States of America (the)': 'United States',
    'Viet Nam': 'Vietnam',
    'Philippines (the)': 'Philippines'
})

In [ ]:
import pandas as pd


# קריאת קובץ ה-GDP המסודר
gdp = pd.read_excel("gdp_clean_for_merge.xlsx", sheet_name="GDP_Long")

In [ ]:
df['Country'] = df['Country'].replace({
    'United States of America (the)': 'United States',
    'Philippines (the)': 'Philippines',
    'Viet Nam': 'Vietnam',
    'Russian Federation (the)': 'Russia',
    'Iran (Islamic Republic of)': 'Iran',
    'Türkiye': 'Turkey'
})

In [ ]:
df = df.merge(
    gdp,
    on=['Country', 'Year'],
    how='left'
)

In [ ]:
print(df.columns.tolist())

['Dis No', 'Year', 'Seq', 'Disaster Group', 'Disaster Subgroup', 'Disaster Type', 'Disaster Subtype', 'Disaster Subsubtype', 'Country', 'ISO', 'Region', 'Continent', 'Origin', 'Associated Dis', 'Associated Dis2', 'OFDA Response', 'Appeal', 'Declaration', 'Dis Mag Value', 'Dis Mag Scale', 'River Basin', 'Start Year', 'Start Month', 'Start Day', 'End Year', 'End Month', 'End Day', 'Total Deaths', 'No Injured', 'No Affected', 'No Homeless', 'Total Affected', "Total Damages ('000 US$)", 'CPI', 'Adm Level', 'Admin1 Code', 'Admin2 Code', 'Geo Locations', 'Disaster Duration (Days)', 'Adjusted Total Damage', 'Country Code', 'GDP_USD']

In [ ]:
df[['Country', 'Year', 'GDP_USD']].head(20)

          Country  Year       GDP_USD
0       Argentina  1970  3.158421e+10
1       Australia  1970  4.139521e+10
2           Benin  1970  3.336277e+08
3      Bangladesh  1970  8.992722e+09
4      Bangladesh  1970  8.992722e+09
5      Bangladesh  1970  8.992722e+09
6      Bangladesh  1970  8.992722e+09
7          Brazil  1970  4.232766e+10
8          Brazil  1970  4.232766e+10
9        Barbados  1970  1.662102e+08
10       Botswana  1970  9.624323e+07
11         Canada  1970  8.819226e+10
12    Switzerland  1970  2.499807e+10
13          China  1970  9.275293e+10
14          China  1970  9.275293e+10
15  Côte d’Ivoire  1970           NaN
16       Colombia  1970  7.198360e+09
17       Colombia  1970  7.198360e+09
18       Colombia  1970  7.198360e+09
19       Colombia  1970  7.198360e+09

In [ ]:
df.rename(
    columns={'GDP_USD': 'GDP'},
    inplace=True
)

In [ ]:
df.head(5)

,Dis No,Year,Seq,Glide,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,Disaster Subsubtype,Event Name,...,Insured Damages ('000 US$),Total Damages ('000 US$),CPI,Adm Level,Admin1 Code,Admin2 Code,Geo Locations,Adjusted Total Damage,Country Code,GDP
0,1970-0013-ARG,1970,13,NaN,Natural,Hydrological,Flood,NaN,NaN,NaN,...,NaN,25000.0,15.001282,NaN,NaN,NaN,NaN,166652.42,ARG,3.158421e+10
1,1970-0109-AUS,1970,109,NaN,Natural,Meteorological,Storm,Tropical cyclone,NaN,Ada,...,NaN,72475.0,15.001282,NaN,NaN,NaN,NaN,483125.37,AUS,4.139521e+10
2,1970-0044-BEN,1970,44,NaN,Natural,Hydrological,Flood,NaN,NaN,NaN,...,NaN,200.0,15.001282,NaN,NaN,NaN,NaN,1333.22,BEN,3.336277e+08
3,1970-0063-BGD,1970,63,NaN,Natural,Meteorological,Storm,Tropical cyclone,NaN,NaN,...,NaN,86400.0,15.001282,NaN,NaN,NaN,NaN,575950.77,BGD,8.992722e+09
4,1970-0026-BGD,1970,26,NaN,Natural,Meteorological,Storm,NaN,NaN,NaN,...,NaN,NaN,15.001282,NaN,NaN,NaN,NaN,NaN,BGD,8.992722e+09

In [ ]:
df['GDP Billions'] = (
    df['GDP'].astype(float) / 1_000_000_000
).round(2)

df[['Country', 'Year', 'GDP Billions']].head(20)

          Country  Year  GDP Billions
0       Argentina  1970         31.58
1       Australia  1970         41.40
2           Benin  1970          0.33
3      Bangladesh  1970          8.99
4      Bangladesh  1970          8.99
5      Bangladesh  1970          8.99
6      Bangladesh  1970          8.99
7          Brazil  1970         42.33
8          Brazil  1970         42.33
9        Barbados  1970          0.17
10       Botswana  1970          0.10
11         Canada  1970         88.19
12    Switzerland  1970         25.00
13          China  1970         92.75
14          China  1970         92.75
15  Côte d’Ivoire  1970           NaN
16       Colombia  1970          7.20
17       Colombia  1970          7.20
18       Colombia  1970          7.20
19       Colombia  1970          7.20

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14644 entries, 0 to 14643
Data columns (total 42 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Dis No                    14644 non-null  object
 1   Year                      14644 non-null  int64
 2   Seq                       14644 non-null  int64
 3   Disaster Group            14644 non-null  object
 4   Disaster Subgroup         14644 non-null  object
 5   Disaster Type             14644 non-null  object
 6   Disaster Subtype          11897 non-null  object
 7   Disaster Subsubtype       1044 non-null   object
 8   Country                   14644 non-null  object
 9   ISO                       14644 non-null  object
 10  Region                    14644 non-null  object
 11  Continent                 14644 non-null  object
 12  Origin                    3780 non-null   object
 13  Associated Dis            3232 non-null   object
 14  Associated Dis2           698 non-null    object
 15  OFDA Response             1450 non-null   object
 16  Appeal                    2440 non-null   object
 17  Declaration               3127 non-null   object
 18  Dis Mag Value             4567 non-null   float64
 19  Dis Mag Scale             13571 non-null  object
 20  River Basin               1285 non-null   object
 21  Start Year                14644 non-null  int64
 22  Start Month               14376 non-null  float64
 23  Start Day                 11577 non-null  float64
 24  End Year                  14644 non-null  int64
 25  End Month                 14095 non-null  float64
 26  End Day                   11650 non-null  float64
 27  Total Deaths              10199 non-null  float64
 28  No Injured                3651 non-null   float64
 29  No Affected               8846 non-null   float64
 30  No Homeless               2249 non-null   float64
 31  Total Affected            11041 non-null  float64
 32  Total Damages ('000 US$)  4863 non-null   float64
 33  CPI                       14644 non-null  float64
 34  Adm Level                 7855 non-null   object
 35  Admin1 Code               4581 non-null   object
 36  Admin2 Code               3965 non-null   object
 37  Geo Locations             7855 non-null   object
 38  Disaster Duration (Days)  11465 non-null  float64
 39  Adjusted Total Damage     4863 non-null   float64
 40  Country Code              11863 non-null  object
 41  GDP                       11739 non-null  float64
dtypes: float64(15), int64(4), object(23)
memory usage: 4.7+ MB

## 2.7 יצירת מדד חומרת ועומצת האסון - נירמול לפי הכמות הרוגים,פצועים והנזק הכלכלי לאחר אינפלציה
חלוקת ל-5 קבוצות שונות עם דרכות חומרה שונות

In [ ]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

severity_cols = [
    'Total Deaths',
    'Total Affected',
    'Adjusted Total Damage'
]

# יצירת עמודות ריקות בדאטה המקורי
df['Severity Score Raw'] = pd.NA
df['Severity Level'] = pd.NA
df['Severity Description'] = pd.NA

# עבודה רק על שורות שיש בהן את כל המדדים
valid_idx = df.dropna(subset=severity_cols).index

scaler = MinMaxScaler()

scaled_values = scaler.fit_transform(
    df.loc[valid_idx, severity_cols]
)

# ציון חומרה רציף
df.loc[valid_idx, 'Severity Score Raw'] = scaled_values.mean(axis=1)

# דירוג 1–5
df.loc[valid_idx, 'Severity Level'] = pd.qcut(
    df.loc[valid_idx, 'Severity Score Raw'],
    q=5,
    labels=[1, 2, 3, 4, 5]
)

severity_labels = {
    1: 'Mild',
    2: 'Moderate',
    3: 'Severe',
    4: 'Very Severe',
    5: 'Catastrophic'
}

df.loc[valid_idx, 'Severity Description'] = (
    df.loc[valid_idx, 'Severity Level']
    .astype(int)
    .map(severity_labels)
)

In [ ]:
df.head(5)

,Dis No,Year,Seq,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,Disaster Subsubtype,Country,ISO,...,Admin1 Code,Admin2 Code,Geo Locations,Disaster Duration (Days),Adjusted Total Damage,Country Code,GDP,Severity Score Raw,Severity Level,Severity Description
0,1970-0013-ARG,1970,13,Natural,Hydrological,Flood,NaN,NaN,Argentina,ARG,...,NaN,NaN,NaN,0.0,166652.42,ARG,3.158421e+10,<NA>,<NA>,<NA>
1,1970-0109-AUS,1970,109,Natural,Meteorological,Storm,Tropical cyclone,NaN,Australia,AUS,...,NaN,NaN,NaN,NaN,483125.37,AUS,4.139521e+10,<NA>,<NA>,<NA>
2,1970-0044-BEN,1970,44,Natural,Hydrological,Flood,NaN,NaN,Benin,BEN,...,NaN,NaN,NaN,NaN,1333.22,BEN,3.336277e+08,<NA>,<NA>,<NA>
3,1970-0063-BGD,1970,63,Natural,Meteorological,Storm,Tropical cyclone,NaN,Bangladesh,BGD,...,NaN,NaN,NaN,0.0,575950.77,BGD,8.992722e+09,0.339216,5,Catastrophic
4,1970-0026-BGD,1970,26,Natural,Meteorological,Storm,NaN,NaN,Bangladesh,BGD,...,NaN,NaN,NaN,0.0,NaN,BGD,8.992722e+09,<NA>,<NA>,<NA>

2.7 הוספת מדד הצפיפות בכל מדינה נלקח מאתר קבוצת הבנק העולמי
קישור: https://data.worldbank.org/indicator/SP.POP.TOTL

In [ ]:
import pandas as pd

# קריאת קובץ האוכלוסייה
population = pd.read_csv("popultion disasters.csv")

# ניקוי רווחים משמות עמודות
population.columns = population.columns.astype(str).str.strip()

# זיהוי אוטומטי של עמודות השנים
year_cols = [
    col for col in population.columns
    if col.isdigit()
]

# הפיכת השנים לעמודה אחת
population_long = population.melt(
    id_vars=['Country Name', 'Country Code'],
    value_vars=year_cols,
    var_name='Year',
    value_name='Population'
)

# שינוי שמות כדי להתאים לדאטה שלך
population_long = population_long.rename(columns={
    'Country Name': 'Country',
    'Country Code': 'Country Code'
})

# המרות סוגי נתונים
population_long['Year'] = pd.to_numeric(population_long['Year'], errors='coerce')
population_long['Population'] = pd.to_numeric(population_long['Population'], errors='coerce')

# התאמת שמות מדינות בדאטה הראשי
df['Country'] = df['Country'].replace({
    'United States of America (the)': 'United States',
    'Viet Nam': 'Vietnam',
    'Philippines (the)': 'Philippines'
})

# מיזוג לפי מדינה ושנה
df = df.merge(
    population_long[['Country', 'Year', 'Population']],
    on=['Country', 'Year'],
    how='left'
)

# יצירת GDP לנפש
df['GDP per Capita'] = df['GDP'] / df['Population']

# בדיקה
df[['Country', 'Year', 'GDP', 'Population', 'GDP per Capita']].head(20)

          Country  Year           GDP   Population  GDP per Capita
0       Argentina  1970  3.158421e+10   23878327.0     1322.714542
1       Australia  1970  4.139521e+10   12507000.0     3309.763063
2           Benin  1970  3.336277e+08    3065057.0      108.848779
3      Bangladesh  1970  8.992722e+09   69058894.0      130.218161
4      Bangladesh  1970  8.992722e+09   69058894.0      130.218161
5      Bangladesh  1970  8.992722e+09   69058894.0      130.218161
6      Bangladesh  1970  8.992722e+09   69058894.0      130.218161
7          Brazil  1970  4.232766e+10   95375651.0      443.799485
8          Brazil  1970  4.232766e+10   95375651.0      443.799485
9        Barbados  1970  1.662102e+08     249387.0      666.475009
10       Botswana  1970  9.624323e+07     590334.0      163.031832
11         Canada  1970  8.819226e+10   21324000.0     4135.821498
12    Switzerland  1970  2.499807e+10    6180877.0     4044.420682
13          China  1970  9.275293e+10  818315000.0      113.346243
14          China  1970  9.275293e+10  818315000.0      113.346243
15  Côte d’Ivoire  1970           NaN          NaN             NaN
16       Colombia  1970  7.198360e+09   20811782.0      345.879102
17       Colombia  1970  7.198360e+09   20811782.0      345.879102
18       Colombia  1970  7.198360e+09   20811782.0      345.879102
19       Colombia  1970  7.198360e+09   20811782.0      345.879102

## 2.8 שמירת הדאטה המעודכן לאחר השינויים והורדה למחשב

In [ ]:
# שמירת הדאטה המעודכן כקובץ CSV
df.to_csv(
    "final_disasters.csv",
    index=False,
    encoding="utf-8-sig"
)

# הורדה למחשב
from google.colab import files

files.download("final_disasters.csv")